CREATE TABLE MST_USER(
	UserId INT NOT NULL CONSTRAINT PK_User_UserId PRIMARY KEY 
						CONSTRAINT DF_User_UserId DEFAULT NEXT VALUE FOR SEQUENTIAL_INCREMENT,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL,
	RoleId int NOT NULL CONSTRAINT FK_User_RoleId FOREIGN KEY (RoleId) REFERENCES MST_USER_ROLES(RoleId),
	IsActive BIT NOT NULL CONSTRAINT DF_IsActive DEFAULT 1
);


